### ISSUE TITLE
Fail to build dbcppp under Windows

### ISSUE THREAD

**Issue by eeyrw** [xR3b0rn/dbcppp#148]
Here are outpus from CMake
```
Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.19045.
The C compiler identification is MSVC 19.29.30154.0
The CXX compiler identification is MSVC 19.29.30154.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Could NOT find Boost (missing: Boost_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:20 (message):
  Boost not found.  Using libdbcppp boost (third-party/boost)


kcd enabled: ON
Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:35 (message):
  LibXml2 was not found.  Using libdbcppp LibXml2 (third-party/libxml2)


CMake Error at D:/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
Call Stack (most recent call first):
  D:/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  D:/CMake/share/cmake-3.21/Modules/FindLibXml2.cmake:108 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  third-party/libxmlmm/CMakeLists.txt:16 (fi
[CMakeOutput.log](https://github.com/xR3b0rn/dbcppp/files/15245116/CMakeOutput.log)
nd_package)


Configuring incomplete, errors occurred!
See also "C:/Users/xxxx/Desktop/dbcppp/build/CMakeFiles/CMakeOutput.log".
```
The log file:
[CMakeOutput.log](https://github.com/xR3b0rn/dbcppp/files/15245132/CMakeOutput.log)

**Comment by xR3b0rn** [comment]
Looks like you did not checkout the submoduls. Try to reclone the project with:
```
git clone --recurse-submodules https://github.com/xR3b0rn/dbcppp.git
```

**Comment by eeyrw** [comment]
I checked the submodules at first and everything is well placed, then I deleted whole repo folder and reclone the project which got same result.

**Comment by DevTheKar** [comment]
I am having the same problem as well while building even after checking out the submodules

**Comment by OwlSurf** [comment]
Hello colleagues! Did someone fixed it? I faced with the same to.

**Comment by OwlSurf** [comment]
I fixed it with :
    apt-get install libxml2-dev

**Comment by DevTheKar** [comment]
I couldn't find any solution on windows still so I gave up and am currently just writing my own parsing library

**Comment by Shady-AusT** [comment]
Using MSYS2 with cmake and Makefiles.
`make -j` fails with a various bunch of errors. 
gcc vresion 14.1.0

**Comment by LiyueAnd** [comment]
> Looks like you did not checkout the submoduls. Try to reclone the project with:
> 
> ```
> git clone --recurse-submodules https://github.com/xR3b0rn/dbcppp.git
> ```

I encountered the same problem. Even after setting some build options in CMakeLists.txt to false, the build still failed. My system is Windows, and I confirmed that I had executed "git clone --recurse-submodules ..."

My changes are as follows:

option(build_kcd "Enable support for KCD parsing" OFF)

option(build_tools "Build dbcppp utility application" OFF)

option(build_tests "Build tests" OFF)

option(build_examples "Build examples" OFF)
